#pragma once 
#include "board_config.h"

#define LVGL_DISPLAY_WIDTH DISPLAY_WIDTH
#define LVGL_DISPLAY_HEIGHT DISPLAY_HEIGHT
#define LVGL_USE_DMA_BUFFER 1
#define LVGL_USE_DOUBLE_BUFFER 1
#define LVGL_SWAP_COLOR_565 1
#define LVGL_TASK_PRIO 5
#define LVGL_TASK_STACK 5120
#define LVGL_DISPLAY_BUFFER_PIXELS (LVGL_DISPLAY_WIDTH * 10)
#define LVGL_MAX_UPDATE_INTERVAL_MS 100