#pragma once

// display
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define GPIO_DISPLAY_SPI_SCLK    9
#define GPIO_DISPLAY_SPI_MOSI    10
#define GPIO_DISPLAY_SPI_MISO    -1
#define GPIO_DISPLAY_SPI_CS      13
#define GPIO_DISPLAY_SPI_DC      11
#define GPIO_DISPLAY_RST   12

#define DISPLAY_SPI_SCLK_HZ     (60 * 1000 * 1000)
#define DISPLAY_SPI_NUM   SPI2_HOST
#define DISPLAY_SPI_MAX_TRANSFER (12*DISPLAY_WIDTH*sizeof(uint16_t))

// backlight
#define GPIO_DISPLAY_BACKLIGHT  14
#define GPIO_DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_BACKLIGHT_PWM_FREQ      4000
#define DISPLAY_BACKLIGHT_PWM_TIMER     0
#define DISPLAY_BACKLIGHT_PWM_CHANNEL   0
#define DISPLAY_BACKLIGHT_DUTY_RES_BIT  LEDC_TIMER_13_BIT
#define DISPLAY_BACKLIGHT_FULL_DUTY     (1<<13) // (1<<13)-1


// input
#define GPIO_LEFT_IR       44
#define GPIO_RIGHT_IR      21
#define GPIO_LEFT_BUTTON   43
#define GPIO_RIGHT_BUTTON  17
#define GPIO_BOOT          0

#define BUTTON_PRESS_LEVEL 0

// audio
#define GPIO_AUDIO_MCLK 38
#define GPIO_AUDIO_WS 41
#define GPIO_AUDIO_BCLK 39
#define GPIO_AUDIO_DIN  40
#define GPIO_AUDIO_DOUT 42

#define GPIO_AUDIO_AMP_PA       18
#define GPIO_AUDIO_AMP_PA_INVERTED  0
#define GPIO_AUDIO_I2C_SDA  48
#define GPIO_AUDIO_I2C_SCL  47
#define GPIO_AUDIO_I2C_PULLUP 0

#define AUDIO_BITS_PER_SAMPLE 16
#define AUDIO_SAMPLE_RATE 24000
#define AUDIO_DEFAULT_SPK_VOL 50
#define AUDIO_DEFAULT_MIC_GAIN 30.0



